# Generated by Django 3.2.4 on 2021-06-03 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210603_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
